name: 'Fetch Data'

on:
  schedule:
    # UTC 时间，并非北京时间
    - cron: '0 0,4,6,23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm@9

      - name: Install Dependencies
        run: pnpm install

      - name: 'Get New Data'
        run: npm run fetch:new

      - name: 'Get Date'
        # run: ACTIONS_ALLOW_UNSECURE_COMMANDS=true;echo "::set-env name=REPORT_DATE::"
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV

      - name: Commit and Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}  # 自动使用内置Token
          branch: master
          author_email: '1576271227@qq.com'
          author_name: 'novlan1'
          force: false  # 避免强制覆盖
          message: "feat: fetch new data ${{ env.REPORT_DATE }}"
